server:
  port: 9527
spring:
  application:
    name: zuul-9527-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,
  instance:
    instance-id: zuul-9527-gateway  #修改Status显示的内容
    prefer-ip-address: true #访问路径显示IP地址
info:
  app.name: 路由微服务
  company.name: iilei
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
zuul:
  prefix: /api  #前缀
  ignored-services: "*"  #忽略所有的，只能使用自定义的路由
  #  ignored-services: provider-dept #单个
  routes:  #域名映射
    provider.serviceId: provider-dept
    provider.path: /provider/**


