server:
  port: 8085

spring:
  application:
    name: provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud01?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&useSSL=false              # 数据库名称
    username: root
    password: iamlilei
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

#mybatis:
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.iilei.api.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml