server:
  port: 3344
spring:
  application:
    name: config-3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Asssssert/spring-cloud-config.git
          username: #  #\u4F60\u7684github\u7528\u6237\u540D
          password: #         #\u4F60\u7684github\u5BC6\u7801
